# -*- coding: utf-8 -*-
# Generated by Django 4.2.17 on 2025-10-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_type", models.CharField(max_length=50)),
                ("tree_count", models.IntegerField()),
                ("tree_age", models.IntegerField()),
                ("detected_count", models.IntegerField()),
                ("weight", models.FloatField()),
                ("total_weight", models.FloatField()),
                ("processing_time", models.FloatField()),
                ("image_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "detection_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MultiDetectionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fruit_type", models.CharField(max_length=50)),
                ("batch_hash", models.CharField(max_length=100, unique=True)),
                ("image_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "multi_detection_batches",
                "ordering": ["-created_at"],
            },
        ),
    ]
