# -*- coding: utf-8 -*-
# Generated by Django 4.2.17 on 2025-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="fruit_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="detectionresult",
            name="tree_age",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multidetectionbatch",
            name="batch_hash",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="multidetectionbatch",
            name="fruit_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
