# Generated by Django 4.2.17 on 2025-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_detectionresult_fruit_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="multidetectionbatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
