# Generated by Django 4.2.17 on 2025-11-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0006_add_composite_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="detectionresult",
            name="detection_fruit_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="detectionresult",
            name="detection_age_fruit_idx",
        ),
        migrations.RemoveIndex(
            model_name="multidetectionbatch",
            name="batch_fruit_created_idx",
        ),
    ]
