# -*- coding: utf-8 -*-
# Generated by Django 4.2.7 on 2025-10-03 18:30

from typing import Any, ClassVar
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: ClassVar[list[Any]] = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("Farm", models.CharField(max_length=250, verbose_name="Farm")),
                ("Field", models.CharField(max_length=250, verbose_name="Field")),
                ("Title", models.CharField(max_length=250, verbose_name="Title")),
                ("State", models.CharField(max_length=250, verbose_name="State")),
                ("Data_time", models.DateTimeField(auto_now_add=True)),
                (
                    "picture",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assets/images",
                        verbose_name="image",
                    ),
                ),
                (
                    "hashing_path",
                    models.CharField(max_length=250, verbose_name="Hashing Path"),
                ),
            ],
        ),
    ]
