# -*- coding: utf-8 -*-
# Generated by Django 4.2.17 on 2025-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dron_map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="Farm",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="Farm"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="Field",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="Field"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="State",
            field=models.CharField(
                db_index=True, max_length=250, verbose_name="State"),
        ),
    ]
