# Generated by Django 4.2.17 on 2025-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dron_map", "0002_alter_projects_farm_alter_projects_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="Data_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
