# Generated by Django 4.2.17 on 2026-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron_map', '0004_add_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='odm_error',
            field=models.TextField(blank=True, help_text='Error message if ODM processing failed', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='odm_status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('disabled', 'Devre Dışı')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='odm_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='NodeODM task UUID', max_length=100, null=True),
        ),
    ]
