[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gdal", "proj", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "/opt/venv/bin/pip install 'email-validator>=1.3.0,<3.0.0' 'flask-login>=0.6.0,<1.0.0' 'flask>=2.3.0,<4.0.0' 'flask-sqlalchemy>=3.0.0,<4.0.0' 'gunicorn>=20.1.0,<22.0.0'",
  "/opt/venv/bin/pip install 'psycopg2-binary>=2.9.0,<3.0.0' 'scipy>=1.9.0,<2.0.0' 'sqlalchemy>=1.4.0,<3.0.0' 'werkzeug>=2.3.0,<4.0.0' 'pandas>=1.5.0,<2.0.0'",
  "/opt/venv/bin/pip install 'opencv-python-headless>=4.5.0,<5.0.0' 'pillow>=9.5.0,<11.0.0' 'numpy>=1.24.0,<2.0.0' 'matplotlib>=3.7.0'",
  "/opt/venv/bin/pip install 'rasterio>=1.3.0,<2.0.0' 'flask-wtf>=1.1.0,<2.0.0' 'wtforms>=3.0.0,<4.0.0' 'psutil>=5.9.0' 'python-dotenv>=1.0.0'"
]

[phases.build]
dependsOn = ["install"]
cmds = ["mkdir -p static/uploads static/results static/detected static/convertor detection_models logs"]

[start]
cmd = "./start.sh"

[variables]
PATH = "/opt/venv/bin:$PATH"
NIXPACKS_PYTHON_VERSION = "3.11"