[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gdal", "proj", "gcc", "git"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "mkdir -p static/uploads static/results static/detected static/convertor detection_models logs",
  "chmod -R 755 static/ logs/"
]

[start]
cmd = "./start.sh"

[variables]
PATH = "/opt/venv/bin:$PATH"
NIXPACKS_PYTHON_VERSION = "3.11"
RAILWAY_ENVIRONMENT = "production"